log:
  level: debug
  disable_sentry: true

db:
  url: db_url

event_tracker:
  contract_address: "0x..."
  start_block: 1321233
  iteration_size: 1000
  rpc: "https://mainnet.infura.io/v3/..."
  runner:
    name: "event_tracker"
    backoff:
      normal_period: 5s
      min_abnormal_period: 5s
      max_abnormal_period: 5s

galxe_submitter:
  credential_id:
  access_token:
  skip_submit: false
